In [1]:
from groove.downbeats import get_measures, get_beat_frames, smooth_power, beat_peaks, get_beat_data, get_audio_data
#from groove.embedding import beat_frames_to_toy
import numpy as np
from groove.embedding import bar_embedding, load_bar_embedding, load_bar_embedding_total
import math

file = '06 Encore A'
ext= 'mp3'

import time

start = time.time()
x = load_bar_embedding_total('milaklaw', [2, 3], [1,1], smooth_power, concatenate=True)
end = time.time()
print(f"Time (new): {end - start}")


start = time.time()
y = load_bar_embedding('milaklaw', [2,3], [1,1], smooth_power, square=False)
end = time.time()
print(f"Time (old): {end - start}")

print(f"Diff: {x[:10]-y[:10]}")

Time (new): 2.81132435798645
Time (old): 84.4648916721344
Diff: [[ 0.00263391 -0.01083595 -0.00278785 -0.01848215  0.01690495]
 [ 0.01293621 -0.01326036  0.00414313 -0.0163548   0.01578459]
 [ 0.01507548 -0.01449213  0.00705595 -0.01631231  0.02066651]
 [ 0.00948068 -0.01562059  0.00042936 -0.01214696  0.02575386]
 [ 0.00855177 -0.0133107   0.00244126 -0.01860227  0.02156461]
 [ 0.01456905 -0.01759542  0.01554837 -0.01344658  0.02109711]
 [ 0.00833797 -0.00976856  0.00343849 -0.02372283  0.01952065]
 [ 0.01414657 -0.01605838  0.00687365 -0.01745981  0.02334918]
 [ 0.00739643 -0.0029966   0.01294725 -0.01090788  0.01774674]
 [-0.00258956 -0.01643185 -0.01476078 -0.01944031  0.02842669]]
